<!DOCTYPE html>
<html lang="pt-BR">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Controle de Serviços - Insect Control Tupí</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700&display=swap" rel="stylesheet">
  <style>
    body {
      font-family: 'Inter', sans-serif;
      background-color: #f8f9fa;
    }

    .container {
      max-width: 900px;
      margin-top: 50px;
      padding: 30px;
      background: white;
      border-radius: 16px;
      box-shadow: 0 0 30px rgba(0, 0, 0, 0.1);
    }

    .logo {
      width: 60px;
      height: 60px;
      object-fit: contain;
      margin-right: 15px;
      border-radius: 50%;
    }

    .header {
      display: flex;
      align-items: center;
      justify-content: center;
      margin-bottom: 30px;
    }

    h1 {
      color: #e60014;
      font-weight: 700;
      text-align: center;
    }

    .btn-danger {
      background-color: #ff0015;
      border: none;
    }

    .btn-danger:hover {
      background-color: #cc0012;
    }

    table th {
      background-color: #e60014;
      color: white;
    }

    .total {
      text-align: right;
      font-size: 1.2rem;
      color: #ff0404;
      font-weight: 600;
    }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <img src="logo.png" alt="Logo Insect Control Tupí" class="logo" />
      <h1>Insect Control Tupí</h1>
    </div>

    <form id="serviceForm" class="row g-3">
      <div class="col-md-3">
        <input type="date" id="data" class="form-control" required />
      </div>
      <div class="col-md-3">
        <input type="text" id="nome" class="form-control" placeholder="Nome do Cliente" required />
      </div>
      <div class="col-md-3">
        <input type="text" id="local" class="form-control" placeholder="Local do Serviço" required />
      </div>
      <div class="col-md-3">
        <select id="tipo" class="form-select" required>
          <option value="" disabled selected>Tipo de Serviço</option>
          <option value="Baratas">Baratas</option>
          <option value="Traças">Traças</option>
          <option value="Cupins">Cupins</option>
          <option value="Outros">Ratos</option>
          <option value="Outros">Lacraias</option>
          <option value="Outros">Limpeza de caixa d'agua</option>
          <option value="Outros">Impermeabilização</option>
          <option value="Outros">Carrapatos</option>
          <option value="Outros">Pulgas</option>
        </select>
      </div>
      <div class="col-md-3">
        <input type="number" id="valor" class="form-control" placeholder="Valor (R$)" step="0.01" required />
      </div>
      <div class="col-md-1 d-grid">
        <button type="submit" class="btn btn-danger">+</button>
      </div>
    </form>

    <div class="table-responsive mt-4">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Data</th>
            <th>Nome</th>
            <th>Local</th>
            <th>Tipo</th>
            <th>Valor (R$)</th>
            <th>Ações</th>
          </tr>
        </thead>
        <tbody id="tabelaServicos"></tbody>
      </table>
    </div>

    <div class="total mt-3">
      Total: R$ <span id="totalValor">0.00</span>
    </div>
  </div>

  <script>
    const form = document.getElementById('serviceForm');
    const tabela = document.getElementById('tabelaServicos');
    const totalSpan = document.getElementById('totalValor');

    let servicos = JSON.parse(localStorage.getItem("servicos")) || [];

    function atualizarTabela() {
      tabela.innerHTML = "";
      let total = 0;

      servicos.forEach((servico, index) => {
        const row = document.createElement("tr");
        row.innerHTML = `
          <td>${servico.data}</td>
          <td>${servico.nome}</td>
          <td>${servico.local}</td>
          <td>${servico.tipo}</td>
          <td>R$ ${parseFloat(servico.valor).toFixed(2)}</td>
          <td><button class="btn btn-sm btn-outline-danger" onclick="removerServico(${index})">Excluir</button></td>
        `;
        tabela.appendChild(row);
        total += parseFloat(servico.valor);
      });

      totalSpan.textContent = total.toFixed(2);
      localStorage.setItem("servicos", JSON.stringify(servicos));
    }

    function removerServico(index) {
      servicos.splice(index, 1);
      atualizarTabela();
    }

    form.addEventListener("submit", (e) => {
      e.preventDefault();
      const novoServico = {
        data: document.getElementById("data").value,
        nome: document.getElementById("nome").value,
        local: document.getElementById("local").value,
        tipo: document.getElementById("tipo").value,
        valor: document.getElementById("valor").value
      };

      servicos.push(novoServico);
      form.reset();
      atualizarTabela();
    });

    atualizarTabela();
  </script>
</body>
</html>
